<a href="https://colab.research.google.com/github/tusharteotia29/Machine-Learning/blob/main/numpy_beginning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Load in numpy

In [2]:
import numpy as np



### The Basics


In [15]:
a=np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [11]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [12]:
#get dimension
b.ndim

2

In [13]:
#Get Shape
b.shape


(2, 3)

In [16]:
#Get type
a.dtype


dtype('int16')

In [18]:
#Get size
a.itemsize
b.itemsize

8

In [20]:
#Get total size
a.nbytes

6

### Accessing/ Changing specific elements, rows. columns ,etc


In [21]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [22]:
#Get a specific element[r,c]
a[1,5]

13

In [23]:
#Get specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
#Get specific row
a[:,2]

array([ 3, 10])

In [25]:
# [start:end:step]
a[0,1:6:2]

array([2, 4, 6])

In [28]:
a[1,5]=20
print(a)

a[:,2]=5
print(a)

a[:,2]=[1,2]
print(a)


[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


##3d examples


In [29]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
# get specific element (work outside in)
# b[0,1,1]
b[:1:1]

array([[[1, 2],
        [3, 4]]])

In [34]:
#replace
b[:,1,:]=[[9,9],[8,8]]

In [35]:
b


array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [37]:
# all 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
#all 1s matrix
np.ones((4,2,2,),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [39]:
#any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [41]:
#any other number(full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [45]:
# random decimal numbers
np.random.rand(4,2,3)
np.random.random_sample(a.shape)

array([[0.9539215 , 0.47345069, 0.4250078 , 0.86213502, 0.31515298,
        0.81252876, 0.06552938],
       [0.39544313, 0.47698155, 0.34586009, 0.6732888 , 0.1800067 ,
        0.90299814, 0.85605731]])

In [49]:
# ranodm integer values
np.random.randint(7,12,size=(3,3))

array([[ 8, 11,  8],
       [ 8,  9,  8],
       [11,  7,  8]])

In [51]:
#the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr=np.array([[1,2,3]])
r1=np