### Load in numpy

In [3]:
import numpy as np



### The Basics


In [4]:
a=np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [5]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
#get dimension
b.ndim

2

In [7]:
#Get Shape
b.shape


(2, 3)

In [8]:
#Get type
a.dtype


dtype('int16')

In [9]:
#Get size
a.itemsize
b.itemsize

8

In [10]:
#Get total size
a.nbytes

6

### Accessing/ Changing specific elements, rows. columns ,etc


In [11]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
#Get a specific element[r,c]
a[1,5]

13

In [13]:
#Get specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
#Get specific row
a[:,2]

array([ 3, 10])

In [15]:
# [start:end:step]
a[0,1:6:2]

array([2, 4, 6])

In [16]:
a[1,5]=20
print(a)

a[:,2]=5
print(a)

a[:,2]=[1,2]
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


##3d examples


In [17]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
# get specific element (work outside in)
# b[0,1,1]
b[:1:1]

array([[[1, 2],
        [3, 4]]])

In [19]:
#replace
b[:,1,:]=[[9,9],[8,8]]

In [20]:
b


array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [21]:
# all 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
#all 1s matrix
np.ones((4,2,2,),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [23]:
#any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [24]:
#any other number(full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [25]:
# random decimal numbers
np.random.rand(4,2,3)
np.random.random_sample(a.shape)

array([[0.36012925, 0.88267635, 0.53267251, 0.98077239, 0.9255147 ,
        0.99192161, 0.21379058],
       [0.69952251, 0.37743494, 0.69619717, 0.39889149, 0.75163029,
        0.47185948, 0.12184664]])

In [26]:
# ranodm integer values
np.random.randint(7,12,size=(3,3))

array([[ 9,  7, 10],
       [ 9, 11,  7],
       [ 7,  7, 11]])

In [27]:
#the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
#repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [33]:
output=np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4,1:4]=z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be careful when copying arrays

In [37]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100

print(a)

[1 2 3]


### Maths

In [38]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [39]:
a+2

array([3, 4, 5, 6])

In [40]:
a-2

array([-1,  0,  1,  2])

In [42]:
a*2

array([2, 4, 6, 8])

In [43]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [44]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [45]:
a**2

array([ 1,  4,  9, 16])

In [46]:
#take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear algebra

In [48]:
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [49]:
#Find theh determinant
c=np.identity(3)
np.linalg.det(c)

1.0

Statistics

In [51]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
np.min(stats)

1

In [53]:
np.max(stats,axis=1)

array([3, 6])

In [54]:
np.sum(stats,axis=0)

array([5, 7, 9])

### Reorganizing arrays

In [58]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

after=before.reshape((8,1))
print(after)

(2, 4)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


### vertical stacking

In [59]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [61]:
#Horizontal stack
h1=np.ones((2,4))
h2=np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### **Miscellaneous**

Load Data from **File**

In [66]:
filedata=np.genfromtxt('data.txt', delimiter=',')

filedata=filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

## **Boolean and advanced Indexing**

In [68]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [69]:
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [70]:
## You can inex with a list in NumPY
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [71]:
np.any(filedata>50,axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [73]:
((filedata>50) & (filedata<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])